/**
 * @description lodash 4.17.5 - 1.6GB - Edited so that variables that have the same names as Netscript functions (`clear` and `exec`) don't increase static RAM usage (by using bracket notation instead of dot notation).
 * @see {@link https://github.com/lodash/lodash|GitHub}
 * @see {@link https://lodash.com/|Lodash}
 */
/**
 * @license
 * Lodash (Custom Build) lodash.com/license | Underscore.js 1.8.3 underscorejs.org/LICENSE
 * Build: `lodash strict exports="none" iife="var _=(function(){%output%;return _;}).call(this);" include="cloneDeep,runInContext" moduleId="none"`
 */
;export var _=function(){function t(t,e,r){switch(r.length){case 0:return t.call(e);case 1:return t.call(e,r[0]);case 2:return t.call(e,r[0],r[1]);case 3:return t.call(e,r[0],r[1],r[2])}return t.apply(e,r)}function e(t,e){for(var r=-1,n=null==t?0:t.length;++r<n&&false!==e(t[r],r,t););return t}function r(t,e){for(var r=-1,n=null==t?0:t.length,o=0,i=[];++r<n;){var c=t[r];e(c,r,t)&&(i[o++]=c)}return i}function n(t,e){for(var r=-1,n=e.length,o=t.length;++r<n;)t[o+r]=e[r];return t}function o(t){return function(e){
  return t(e)}}function i(t,e){return function(r){return t(e(r))}}var c=1/0,a=/\.|\[(?:[^[\]]*|(["'])(?:(?!\1)[^\\]|\\.)*?\1)\]/,u=/^\w*$/,f=/[^.[\]]+|\[(?:(-?\d+(?:\.\d+)?)|(["'])((?:(?!\2)[^\\]|\\.)*?)\2)\]|(?=(?:\.|\[\])(?:\.|\[\]|$))/g,l=/[\\^$.*+?()[\]{}|]/g,s=/\\(\\)?/g,b=/\w*$/,p=/^\[object .+?Constructor\]$/,y=/^(?:0|[1-9]\d*)$/,h="Array Buffer DataView Date Error Float32Array Float64Array Function Int8Array Int16Array Int32Array Map Math Object Promise RegExp Set String Symbol TypeError Uint8Array Uint8ClampedArray Uint16Array Uint32Array WeakMap _ clearTimeout isFinite parseInt setTimeout".split(" "),v={};
  v["[object Float32Array]"]=v["[object Float64Array]"]=v["[object Int8Array]"]=v["[object Int16Array]"]=v["[object Int32Array]"]=v["[object Uint8Array]"]=v["[object Uint8ClampedArray]"]=v["[object Uint16Array]"]=v["[object Uint32Array]"]=true,v["[object Arguments]"]=v["[object Array]"]=v["[object ArrayBuffer]"]=v["[object Boolean]"]=v["[object DataView]"]=v["[object Date]"]=v["[object Error]"]=v["[object Function]"]=v["[object Map]"]=v["[object Number]"]=v["[object Object]"]=v["[object RegExp]"]=v["[object Set]"]=v["[object String]"]=v["[object WeakMap]"]=false;
  var j={};j["[object Arguments]"]=j["[object Array]"]=j["[object ArrayBuffer]"]=j["[object DataView]"]=j["[object Boolean]"]=j["[object Date]"]=j["[object Float32Array]"]=j["[object Float64Array]"]=j["[object Int8Array]"]=j["[object Int16Array]"]=j["[object Int32Array]"]=j["[object Map]"]=j["[object Number]"]=j["[object Object]"]=j["[object RegExp]"]=j["[object Set]"]=j["[object String]"]=j["[object Symbol]"]=j["[object Uint8Array]"]=j["[object Uint8ClampedArray]"]=j["[object Uint16Array]"]=j["[object Uint32Array]"]=true,
  j["[object Error]"]=j["[object Function]"]=j["[object WeakMap]"]=false;var _,d=typeof global=="object"&&global&&global.Object===Object&&global,g=typeof self=="object"&&self&&self.Object===Object&&self,A=d||g||Function("return this")(),m=(g=typeof exports=="object"&&exports&&!exports.nodeType&&exports)&&typeof module=="object"&&module&&!module.nodeType&&module,w=m&&m.exports===g,d=w&&d.process;t:{try{_=d&&d.binding&&d.binding("util");break t}catch(t){}_=void 0}var S=_&&_.isMap,O=_&&_.isSet,z=_&&_.isTypedArray,x=function _(d){
  function g(){}function m(t){var e=-1,r=null==t?0:t.length;for(this["clear"]();++e<r;){var n=t[e];this.set(n[0],n[1])}}function F(t){var e=-1,r=null==t?0:t.length;for(this["clear"]();++e<r;){var n=t[e];this.set(n[0],n[1])}}function I(t){var e=-1,r=null==t?0:t.length;for(this["clear"]();++e<r;){var n=t[e];this.set(n[0],n[1])}}function U(t){this.size=(this.__data__=new F(t)).size}function M(t,e){var r=Ue(t),n=!r&&Ie(t),o=!r&&!n&&Me(t),i=!r&&!n&&!o&&De(t);if(r=r||n||o||i){for(var n=t.length,c=Pt,a=-1,u=Array(n);++a<n;)u[a]=c(a);
  n=u}else n=[];var f,c=n.length;for(f in t)!e&&!Lt.call(t,f)||r&&("length"==f||o&&("offset"==f||"parent"==f)||i&&("buffer"==f||"byteLength"==f||"byteOffset"==f)||ft(f,c))||n.push(f);return n}function k(t,e,r){var n=t[e];Lt.call(t,e)&&vt(n,r)&&(void 0!==r||e in t)||P(t,e,r)}function E(t,e){for(var r=t.length;r--;)if(vt(t[r][0],e))return r;return-1}function D(t,e){return t&&Y(e,Ot(e),t)}function B(t,e){return t&&Y(e,zt(e),t)}function P(t,e,r){"__proto__"==e&&re?re(t,e,{configurable:true,enumerable:true,
  value:r,writable:true}):t[e]=r}function $(t,r,n,o,i,c){var a,u=1&r,f=2&r,l=4&r;if(n&&(a=i?n(t,o,i,c):n(t)),void 0!==a)return a;if(!gt(t))return t;if(o=Ue(t)){if(a=it(t),!u)return X(t,a)}else{var s=ze(t),b="[object Function]"==s||"[object GeneratorFunction]"==s;if(Me(t))return K(t,u);if("[object Object]"==s||"[object Arguments]"==s||b&&!i){if(a=f||b?{}:ct(t),!u)return f?tt(t,B(a,t)):Z(t,D(a,t))}else{if(!j[s])return i?t:{};a=at(t,s,u)}}if(c||(c=new U),i=c.get(t))return i;if(c.set(t,a),Ee(t))return t.forEach(function(e){
  a.add($(e,r,n,e,t,c))}),a;if(ke(t))return t.forEach(function(e,o){a.set(o,$(e,r,n,o,t,c))}),a;var f=l?f?rt:et:f?zt:Ot,p=o?void 0:f(t);return e(p||t,function(e,o){p&&(o=e,e=t[o]),k(a,o,$(e,r,n,o,t,c))}),a}function C(t,e,r,o,i){var c=-1,a=t.length;for(r||(r=ut),i||(i=[]);++c<a;){var u=t[c];0<e&&r(u)?1<e?C(u,e-1,r,o,i):n(i,u):o||(i[i.length]=u)}return i}function T(t,e,r){return e=e(t),Ue(t)?e:n(e,r(t))}function V(t){if(null==t)return void 0===t?"[object Undefined]":"[object Null]";if(ee&&ee in Dt(t)){
  var e=Lt.call(t,ee),r=t[ee];try{t[ee]=void 0;var n=true}catch(t){}var o=Nt.call(t);n&&(e?t[ee]=r:delete t[ee]),t=o}else t=Nt.call(t);return t}function R(t){return At(t)&&"[object Arguments]"==V(t)}function L(t){return At(t)&&"[object Map]"==ze(t)}function W(t){return At(t)&&"[object Set]"==ze(t)}function N(t){return At(t)&&dt(t.length)&&!!v[V(t)]}function G(t,e){return q(t,e,function(e,r){return St(t,r)})}function q(t,e,r){for(var n=-1,o=e.length,i={};++n<o;){var c,a=e[n];c=t;for(var u=a,u=J(u,c),f=0,l=u.length;null!=c&&f<l;)c=c[bt(u[f++])];
  if(c=f&&f==l?c:void 0,r(c,a)){var s=i,a=J(a,t);if(gt(s))for(a=J(a,s),u=-1,f=a.length,l=f-1;null!=s&&++u<f;){var b=bt(a[u]),p=c;if(u!=l){var y=s[b],p=void 0;void 0===p&&(p=gt(y)?y:ft(a[u+1])?[]:{})}k(s,b,p),s=s[b]}}}return i}function H(t){if(typeof t=="string")return t;if(Ue(t)){for(var e=H,r=-1,n=null==t?0:t.length,o=Array(n);++r<n;)o[r]=e(t[r],r,t);return o+""}return mt(t)?Ae?Ae.call(t):"":(e=t+"","0"==e&&1/t==-c?"-0":e)}function J(t,e){if(Ue(t))return t;var r;return Ue(t)?r=false:(r=typeof t,r=!("number"!=r&&"symbol"!=r&&"boolean"!=r&&null!=t&&!mt(t))||(u.test(t)||!a.test(t)||null!=e&&t in Dt(e))),
  r?[t]:Fe(wt(t))}function K(t,e){if(e)return t.slice();var r=t.length,r=Kt?Kt(r):new t.constructor(r);return t.copy(r),r}function Q(t){var e=new t.constructor(t.byteLength);return new Jt(e).set(new Jt(t)),e}function X(t,e){var r=-1,n=t.length;for(e||(e=Mt(n));++r<n;)e[r]=t[r];return e}function Y(t,e,r,n){var o=!r;r||(r={});for(var i=-1,c=e.length;++i<c;){var a=e[i],u=n?n(r[a],t[a],a,r,t):void 0;void 0===u&&(u=t[a]),o?P(r,a,u):k(r,a,u)}return r}function Z(t,e){return Y(t,Se(t),e)}function tt(t,e){return Y(t,Oe(t),e);
  }function et(t){return T(t,Ot,Se)}function rt(t){return T(t,zt,Oe)}function nt(t,e){var r=t.__data__,n=typeof e;return("string"==n||"number"==n||"symbol"==n||"boolean"==n?"__proto__"!==e:null===e)?r[typeof e=="string"?"string":"hash"]:r.map}function ot(t,e){var r,n=null==t?void 0:t[e];return r=!(!gt(n)||Wt&&Wt in n)&&(_t(n)?Gt:p).test(pt(n)),r?n:void 0}function it(t){var e=t.length,r=new t.constructor(e);return e&&"string"==typeof t[0]&&Lt.call(t,"index")&&(r.index=t.index,r.input=t.input),r}function ct(t){
  return typeof t.constructor!="function"||lt(t)?{}:me(Qt(t))}function at(t,e,r){var n=t.constructor;switch(e){case"[object ArrayBuffer]":return Q(t);case"[object Boolean]":case"[object Date]":return new n(+t);case"[object DataView]":return e=r?Q(t.buffer):t.buffer,new t.constructor(e,t.byteOffset,t.byteLength);case"[object Float32Array]":case"[object Float64Array]":case"[object Int8Array]":case"[object Int16Array]":case"[object Int32Array]":case"[object Uint8Array]":case"[object Uint8ClampedArray]":
  case"[object Uint16Array]":case"[object Uint32Array]":return e=r?Q(t.buffer):t.buffer,new t.constructor(e,t.byteOffset,t.length);case"[object Map]":return new n;case"[object Number]":case"[object String]":return new n(t);case"[object RegExp]":return e=new t.constructor(t.source,b["exec"](t)),e.lastIndex=t.lastIndex,e;case"[object Set]":return new n;case"[object Symbol]":return ge?Dt(ge.call(t)):{}}}function ut(t){return Ue(t)||Ie(t)||!!(te&&t&&t[te])}function ft(t,e){var r=typeof t;return e=null==e?9007199254740991:e,
  !!e&&("number"==r||"symbol"!=r&&y.test(t))&&-1<t&&0==t%1&&t<e}function lt(t){var e=t&&t.constructor;return t===(typeof e=="function"&&e.prototype||Tt)}function st(e,r,n){return r=ce(void 0===r?e.length-1:r,0),function(){for(var o=arguments,i=-1,c=ce(o.length-r,0),a=Mt(c);++i<c;)a[i]=o[r+i];for(i=-1,c=Mt(r+1);++i<r;)c[i]=o[i];return c[r]=n(a),t(e,this,c)}}function bt(t){if(typeof t=="string"||mt(t))return t;var e=t+"";return"0"==e&&1/t==-c?"-0":e}function pt(t){if(null!=t){try{return Rt.call(t)}catch(t){}
  return t+""}return""}function yt(t){return(null==t?0:t.length)?C(t,1):[]}function ht(t,e){if(typeof t!="function"||null!=e&&typeof e!="function")throw new $t("Expected a function");var r=function(){var n=arguments,o=e?e.apply(this,n):n[0],i=r.cache;return i.has(o)?i.get(o):(n=t.apply(this,n),r.cache=i.set(o,n)||i,n)};return r.cache=new(ht.Cache||I),r}function vt(t,e){return t===e||t!==t&&e!==e}function jt(t){return null!=t&&dt(t.length)&&!_t(t)}function _t(t){return!!gt(t)&&(t=V(t),"[object Function]"==t||"[object GeneratorFunction]"==t||"[object AsyncFunction]"==t||"[object Proxy]"==t);
  }function dt(t){return typeof t=="number"&&-1<t&&0==t%1&&9007199254740991>=t}function gt(t){var e=typeof t;return null!=t&&("object"==e||"function"==e)}function At(t){return null!=t&&typeof t=="object"}function mt(t){return typeof t=="symbol"||At(t)&&"[object Symbol]"==V(t)}function wt(t){return null==t?"":H(t)}function St(t,e){var r;if(r=null!=t){r=t;var n;n=J(e,r);for(var o=-1,i=n.length,c=false;++o<i;){var a=bt(n[o]);if(!(c=null!=r&&null!=r&&a in Dt(r)))break;r=r[a]}c||++o!=i?r=c:(i=null==r?0:r.length,
  r=!!i&&dt(i)&&ft(a,i)&&(Ue(r)||Ie(r)))}return r}function Ot(t){if(jt(t))t=M(t);else if(lt(t)){var e,r=[];for(e in Dt(t))Lt.call(t,e)&&"constructor"!=e&&r.push(e);t=r}else t=ie(t);return t}function zt(t){if(jt(t))t=M(t,true);else if(gt(t)){var e,r=lt(t),n=[];for(e in t)("constructor"!=e||!r&&Lt.call(t,e))&&n.push(e);t=n}else{if(e=[],null!=t)for(r in Dt(t))e.push(r);t=e}return t}function xt(t){return function(){return t}}function Ft(t){return t}function It(){return[]}function Ut(){return false}d=null==d?A:x.defaults(A.Object(),d,x.pick(A,h));
  var Mt=d.Array,kt=d.Date,Et=d.Math,Dt=d.Object,Bt=d.RegExp,Pt=d.String,$t=d.TypeError,Ct=Mt.prototype,Tt=Dt.prototype,Vt=d["__core-js_shared__"],Rt=d.Function.prototype.toString,Lt=Tt.hasOwnProperty,Wt=function(){var t=/[^.]+$/["exec"](Vt&&Vt.keys&&Vt.keys.IE_PROTO||"");return t?"Symbol(src)_1."+t:""}(),Nt=Tt.toString;Rt.call(Dt);var Gt=Bt("^"+Rt.call(Lt).replace(l,"\\$&").replace(/hasOwnProperty|(function).*?(?=\\\()| for .+?(?=\\\])/g,"$1.*?")+"$"),qt=w?d.Buffer:void 0,Ht=d.Symbol,Jt=d.Uint8Array,Kt=qt?qt.allocUnsafe:void 0,Qt=i(Dt.getPrototypeOf,Dt),Xt=Dt.create,Yt=Tt.propertyIsEnumerable,Zt=Ct.splice,te=Ht?Ht.isConcatSpreadable:void 0,ee=Ht?Ht.toStringTag:void 0,re=function(){
  try{var t=ot(Dt,"defineProperty");return t({},"",{}),t}catch(t){}}(),ne=Dt.getOwnPropertySymbols,oe=qt?qt.isBuffer:void 0,ie=i(Dt.keys,Dt),ce=Et.max,ae=kt.now,ue=ot(d,"DataView"),fe=ot(d,"Map"),le=ot(d,"Promise"),se=ot(d,"Set"),be=ot(d,"WeakMap"),pe=ot(Dt,"create"),ye=pt(ue),he=pt(fe),ve=pt(le),je=pt(se),_e=pt(be),de=Ht?Ht.prototype:void 0,ge=de?de.valueOf:void 0,Ae=de?de.toString:void 0,me=function(){function t(){}return function(e){return gt(e)?Xt?Xt(e):(t.prototype=e,e=new t,t.prototype=void 0,
  e):{}}}();m.prototype["clear"]=function(){this.__data__=pe?pe(null):{},this.size=0},m.prototype.delete=function(t){return t=this.has(t)&&delete this.__data__[t],this.size-=t?1:0,t},m.prototype.get=function(t){var e=this.__data__;return pe?(t=e[t],"__lodash_hash_undefined__"===t?void 0:t):Lt.call(e,t)?e[t]:void 0},m.prototype.has=function(t){var e=this.__data__;return pe?void 0!==e[t]:Lt.call(e,t)},m.prototype.set=function(t,e){var r=this.__data__;return this.size+=this.has(t)?0:1,r[t]=pe&&void 0===e?"__lodash_hash_undefined__":e,
  this},F.prototype["clear"]=function(){this.__data__=[],this.size=0},F.prototype.delete=function(t){var e=this.__data__;return t=E(e,t),!(0>t)&&(t==e.length-1?e.pop():Zt.call(e,t,1),--this.size,true)},F.prototype.get=function(t){var e=this.__data__;return t=E(e,t),0>t?void 0:e[t][1]},F.prototype.has=function(t){return-1<E(this.__data__,t)},F.prototype.set=function(t,e){var r=this.__data__,n=E(r,t);return 0>n?(++this.size,r.push([t,e])):r[n][1]=e,this},I.prototype["clear"]=function(){this.size=0,this.__data__={
  hash:new m,map:new(fe||F),string:new m}},I.prototype.delete=function(t){return t=nt(this,t).delete(t),this.size-=t?1:0,t},I.prototype.get=function(t){return nt(this,t).get(t)},I.prototype.has=function(t){return nt(this,t).has(t)},I.prototype.set=function(t,e){var r=nt(this,t),n=r.size;return r.set(t,e),this.size+=r.size==n?0:1,this},U.prototype["clear"]=function(){this.__data__=new F,this.size=0},U.prototype.delete=function(t){var e=this.__data__;return t=e.delete(t),this.size=e.size,t},U.prototype.get=function(t){
  return this.__data__.get(t)},U.prototype.has=function(t){return this.__data__.has(t)},U.prototype.set=function(t,e){var r=this.__data__;if(r instanceof F){var n=r.__data__;if(!fe||199>n.length)return n.push([t,e]),this.size=++r.size,this;r=this.__data__=new I(n)}return r.set(t,e),this.size=r.size,this};var we=re?function(t,e){return re(t,"toString",{configurable:true,enumerable:false,value:xt(e),writable:true})}:Ft,Se=ne?function(t){return null==t?[]:(t=Dt(t),r(ne(t),function(e){return Yt.call(t,e)}))}:It,Oe=ne?function(t){
  for(var e=[];t;)n(e,Se(t)),t=Qt(t);return e}:It,ze=V;(ue&&"[object DataView]"!=ze(new ue(new ArrayBuffer(1)))||fe&&"[object Map]"!=ze(new fe)||le&&"[object Promise]"!=ze(le.resolve())||se&&"[object Set]"!=ze(new se)||be&&"[object WeakMap]"!=ze(new be))&&(ze=function(t){var e=V(t);if(t=(t="[object Object]"==e?t.constructor:void 0)?pt(t):"")switch(t){case ye:return"[object DataView]";case he:return"[object Map]";case ve:return"[object Promise]";case je:return"[object Set]";case _e:return"[object WeakMap]";
  }return e});var xe=function(t){var e=0,r=0;return function(){var n=ae(),o=16-(n-r);if(r=n,0<o){if(800<=++e)return arguments[0]}else e=0;return t.apply(void 0,arguments)}}(we),Fe=function(t){t=ht(t,function(t){return 500===e.size&&e["clear"](),t});var e=t.cache;return t}(function(t){var e=[];return 46===t.charCodeAt(0)&&e.push(""),t.replace(f,function(t,r,n,o){e.push(n?o.replace(s,"$1"):r||t)}),e});ht.Cache=I;var Ie=R(function(){return arguments}())?R:function(t){return At(t)&&Lt.call(t,"callee")&&!Yt.call(t,"callee");
  },Ue=Mt.isArray,Me=oe||Ut,ke=S?o(S):L,Ee=O?o(O):W,De=z?o(z):N,Be=function(t,e){return xe(st(t,e,Ft),t+"")}(function(t,e){t=Dt(t);var r,n=-1,o=e.length,i=2<o?e[2]:void 0;if(r=i){r=e[0];var c=e[1];if(gt(i)){var a=typeof c;r=!!("number"==a?jt(i)&&ft(c,i.length):"string"==a&&c in i)&&vt(i[c],r)}else r=false}for(r&&(o=1);++n<o;)for(i=e[n],r=zt(i),c=-1,a=r.length;++c<a;){var u=r[c],f=t[u];(void 0===f||vt(f,Tt[u])&&!Lt.call(t,u))&&(t[u]=i[u])}return t}),Pe=function(t){return xe(st(t,void 0,yt),t+"")}(function(t,e){
  return null==t?{}:G(t,e)});return g.constant=xt,g.defaults=Be,g.flatten=yt,g.keys=Ot,g.keysIn=zt,g.memoize=ht,g.pick=Pe,g.cloneDeep=function(t){return $(t,5)},g.eq=vt,g.hasIn=St,g.identity=Ft,g.isArguments=Ie,g.isArray=Ue,g.isArrayLike=jt,g.isBuffer=Me,g.isFunction=_t,g.isLength=dt,g.isMap=ke,g.isObject=gt,g.isObjectLike=At,g.isSet=Ee,g.isSymbol=mt,g.isTypedArray=De,g.stubArray=It,g.stubFalse=Ut,g.runInContext=_,g.toString=wt,g.VERSION="4.17.5",g}();return x}.call(this);
